# Tag: wxwmatt/rails:5.2.6.2-alpine3.15
FROM ruby:2.7.5-alpine3.15

RUN set -eux; \
        apk add --no-cache \
                sqlite-dev \
                mariadb-dev \
                postgresql-dev \
                ruby-dev \
                nodejs \
                npm \
                yarn \
                make \
                musl-dev \
                build-base \
                tzdata \
                curl \
                git \
#https://pkgs.alpinelinux.org/package/edge/main/aarch64/build-base
                build-base \
#https://nokogiri.org/tutorials/installing_nokogiri.html#linux-musl-error-loading-shared-library
                gcompat \
#https://en.wikipedia.org/wiki/BusyBox
                busybox \
                ca-certificates \
                libffi-dev \
                libsodium-dev \
                imagemagick \
                curl-dev \
                vips-dev \
        ;
RUN mkdir -p /bundle/cache /app
ENV GEM_HOME=/bundle
ENV PATH=$PATH:/bundle/bin
ENV HOME=/app
RUN gem install nokogiri --platform=ruby
RUN gem install rails -v 5.2.6.2

# Pre-install gems for a typical Rails project
RUN cd /tmp && rails new for_installing_gems_mysql --database=mysql
RUN cd /tmp && rails new for_installing_gems_postgres --database=postgresql
RUN cd /tmp && rails new for_installing_gems_sqlite3 --database=sqlite3

# make bundle directory writable
RUN chmod -Rf a+rw /bundle /app

# Cleanup
RUN rm -rf /tmp/for_installing_gems_mysql
RUN rm -rf /tmp/for_installing_gems_postgres
RUN rm -rf /tmp/for_installing_gems_sqlite3
