FROM ruby:3.0.3-alpine3.15

RUN set -eux; \
        apk add --no-cache \
                sqlite-dev \
                mariadb-dev \
                postgresql-dev \
                ruby-dev \
                nodejs \
                npm \
                yarn \
                make \
                musl-dev \
                build-base \
                tzdata \
                curl \
                git \
#https://pkgs.alpinelinux.org/package/edge/main/aarch64/build-base
                build-base \
#https://nokogiri.org/tutorials/installing_nokogiri.html#linux-musl-error-loading-shared-library
                gcompat \
#https://en.wikipedia.org/wiki/BusyBox
                busybox \
                ca-certificates \
                libffi-dev \
                libsodium-dev \
                imagemagick \
                curl-dev \
                vips-dev \

        ;
RUN mkdir /bundle
RUN chmod a+x /bundle
ENV GEM_HOME=/bundle
ENV PATH=$PATH:/bundle/bin
ENV HOME=/app
RUN gem install nokogiri --platform=ruby
RUN gem install rails -v 7.0.1
RUN cd /tmp && rails new for_installing_gems_mysql --database=mysql
RUN cd /tmp && rails new for_installing_gems_postgres --database=postgresql
RUN cd /tmp && rails new for_installing_gems_sqlite3 --database=sqlite3
RUN rm -rf /tmp/for_installing_gems_mysql
RUN rm -rf /tmp/for_installing_gems_postgres
RUN rm -rf /tmp/for_installing_gems_sqlite3
