FROM {{ rails_base_tag }}

RUN mkdir -p /app
WORKDIR /app

ENV HOME /app
ENV RAILS_ENV production
ENV RAILS_SERVE_STATIC_FILES true
ENV RAILS_LOG_TO_STDOUT true

COPY Gemfile Gemfile.lock ./

RUN bundle config --global frozen 1
RUN bundle config set --local without 'development test'
RUN bundle install

COPY . ./
RUN bundle exec rake assets:precompile

EXPOSE 3000
CMD ["rails", "server", "-b", "0.0.0.0"]
